import manager.TaskManager;
import storageTasks.*;

public static void main(String[] args) {
    TaskManager manager = new TaskManager();
    Task task1 = new Task("title task1", "desc task1");
    manager.addTask(task1);
    Task task2 = new Task("title task2", "desc task2");
    manager.addTask(task2);
    Epic epic1 = new Epic("title epic1", "desc epic1");
    manager.addEpic(epic1);
    Epic epic2 = new Epic("title epic2", "desc epic2");
    manager.addEpic(epic2);
    Subtask subtask1 = new Subtask("title subtask1", "desc subtask1", epic1.getId());
    manager.addSubtask(subtask1);
    Subtask subtask2 = new Subtask("title subtask2", "desc subtask2", epic1.getId());
    manager.addSubtask(subtask2);
    Subtask subtask3 = new Subtask("title subtask3", "desc subtask3", epic2.getId());
    manager.addSubtask(subtask3);
    System.out.println("Список задач: " + manager.getAllTask());
    System.out.println("Список эпиков: " + manager.getAllEpic());
    System.out.println("Список подзадач: " + manager.getAllSubtask());
    System.out.println();
    task1.setStatus(Status.DONE);
    manager.updateTask(task1);
    task2.setStatus(Status.IN_PROGRESS);
    manager.updateTask(task2);
    subtask1.setStatus(Status.DONE);
    manager.updateSubtask(subtask1);
    subtask3.setStatus(Status.DONE);
    manager.updateSubtask(subtask3);
    System.out.println("Список задач: " + manager.getAllTask());
    System.out.println("Список эпиков: " + manager.getAllEpic());
    System.out.println("Список подзадач: " + manager.getAllSubtask());
    System.out.println();
    manager.deleteTask(task1.getId());
    manager.deleteEpic(epic1.getId());
    System.out.println("Список задач: " + manager.getAllTask());
    System.out.println("Список эпиков: " + manager.getAllEpic());
    System.out.println("Список подзадач: " + manager.getAllSubtask());
}